import { questRepo } from "../repositories.js";
import { buildWellbeingSnapshot, generateDailyQuests } from "../ai.js";
import { grantXpAndCelebrate } from "./_actions.js";
import { icon } from "../icons.js";

export async function render(container) {
  container.innerHTML = `
    <div class="screen-title"><h2>Today's quests</h2><p class="muted">Generated by the AI engine from your real data</p></div>
    <div id="quests-body">${`<div class="skel" style="height:200px;border-radius:14px;"></div>`}</div>
  `;

  let quests = await questRepo.todaysQuests();
  if (quests.length === 0) {
    const snapshot = await buildWellbeingSnapshot();
    const generated = generateDailyQuests(snapshot);
    quests = await questRepo.setQuests(generated);
  }

  draw();

  function draw() {
    const done = quests.filter((q) => q.completed).length;
    container.querySelector("#quests-body").innerHTML = `
      <div class="glass-card section">
        <div class="flex-between"><h3 style="margin:0;">Progress</h3><span class="muted">${done}/${quests.length}</span></div>
        <div class="xp-bar"><div style="width:${quests.length ? (done/quests.length)*100 : 0}%"></div></div>
      </div>
      <div class="list" id="quests-list"></div>
    `;
    const list = container.querySelector("#quests-list");
    quests.forEach((q) => {
      const item = document.createElement("div");
      item.className = "list-item";
      item.innerHTML = `
        <span class="icon-wrap">${icon(q.icon || "target", { size: 17 })}</span>
        <div class="main"><div class="title">${q.title}</div><div class="sub">+${q.xp} XP · +${q.coins} coins</div></div>
        <button class="checkbox-btn ${q.completed ? "done" : ""}" ${q.completed ? "disabled" : ""}></button>
      `;
      item.querySelector("button").addEventListener("click", async () => {
        await questRepo.complete(q.id);
        q.completed = true;
        await grantXpAndCelebrate(q.xp, "quest: " + q.title, q.coins);
        draw();
      });
      list.appendChild(item);
    });
  }
}
